name: Python Package
on: push

jobs:
  publishPythonZip:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Zip Python Udf
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          zip -r python_udf_${RELEASE_VERSION}.zip $GITHUB_WORKSPACE/python_functions -x "*/__init__.py
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "python_udf.zip,python_functions/requirements.txt,python_functions/data/*"
          allowUpdates: true
          omitNameDuringUpdate: true
          omitBodyDuringUpdate: true
          omitPrereleaseDuringUpdate: true
          token: ${{ secrets.GITHUB_TOKEN }}
